/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function loadSshKeyInfo(keyPath: string): string
export declare function testCertificateDetection(certPath: string): boolean
export declare function sshConnect(host: string, port: number, username: string, keyPath: string, certPath?: string | undefined | null): Promise<number>
export declare function sshExec(sessionId: number, command: string): Promise<string>
export declare function sshForwardPort(sessionId: number, localPort: number, remoteHost: string, remotePort: number): Promise<number>
export declare function sshUploadFile(sessionId: number, localPath: string, remotePath: string): Promise<void>
export declare function sshDisconnect(sessionId: number): Promise<void>
